const globals = require('globals');

module.exports = [
    {
        files: ['**/*.js'],
        languageOptions: {
            ecmaVersion: 2021,
            sourceType: 'commonjs',
            globals: {
                ...globals.node,
            },
        },
        rules: {
            'no-unused-vars': ['warn', { argsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' }],
            'no-undef': 'error',
            'no-redeclare': 'error',
            'no-dupe-keys': 'error',
            'no-duplicate-case': 'error',
            'no-unreachable': 'error',
            'no-constant-condition': 'warn',
            'no-empty': 'warn',
            'no-extra-semi': 'warn',
            'no-unexpected-multiline': 'error',
            'no-sparse-arrays': 'warn',
            'no-unsafe-negation': 'error',
            'use-isnan': 'error',
            'valid-typeof': 'error',
            'no-self-compare': 'warn',
            'no-template-curly-in-string': 'error',
            'no-async-promise-executor': 'error',
            'no-await-in-loop': 'off',
            'no-compare-neg-zero': 'error',
            'no-cond-assign': 'error',
            'no-debugger': 'error',
            'no-dupe-args': 'error',
            'no-func-assign': 'error',
            'no-irregular-whitespace': 'warn',
            'no-loss-of-precision': 'error',
            'no-misleading-character-class': 'warn',
            'no-new-native-nonconstructor': 'error',
            'no-obj-calls': 'error',
            'no-promise-executor-return': 'off',
            'no-prototype-builtins': 'warn',
            'no-shadow-restricted-names': 'error',
            'no-this-before-super': 'error',
            'no-unsafe-optional-chaining': 'error',
            'no-unused-labels': 'error',
            'no-useless-backreference': 'error',
            'no-useless-catch': 'warn',
            'no-useless-escape': 'warn',
            'no-with': 'error',
            'require-yield': 'error',
        },
    },
];