const SCRYFALL_DELAY = 600;

const DICIONARIO_PT_EN = {
    'raio': 'Lightning Bolt',
    'conterspell': 'Counterspell',
    'contrafeitiço': 'Counterspell',
    'contrafeitico': 'Counterspell',
    'girino': 'Giant Growth',
    'crescimento gigante': 'Giant Growth',
    'terror': 'Terror',
    'praga': 'Plague',
    'anjo': 'Angel of Grace',
    'dragão': 'Dragon Whelp',
    'dragao': 'Dragon Whelp',
    'elfo': 'Elvish Mystic',
    'duende': 'Goblin Guide',
    'mago': 'Snapcaster Mage',
    'cavaleiro': 'Knight of the White Orchid',
    'guerreiro': 'Warrior en-Kor',
    'feiticeiro': 'Sorcerer',
    'planinauta': 'Planeswalker',
    'encantamento': 'Enchantment',
    'artefato': 'Artifact',
    'terreno': 'Land',
    'criatura': 'Creature',
    'instantânea': 'Instant',
    'instantanea': 'Instant',
    'feitiço': 'Sorcery',
    'caminhante de planos': 'Planeswalker',
    'destruição': 'Destroy',
    'destruicao': 'Destroy',
    'exílio': 'Exile',
    'exilio': 'Exile',
    'ressurreição': 'Resurrection',
    'jogar': 'Cast',
    'sacrificar': 'Sacrifice',
    'compra': 'Draw',
    'comprar': 'Draw',
    'ilha': 'Island',
    'montanha': 'Mountain',
    'floresta': 'Forest',
    'pântano': 'Swamp',
    'pantano': 'Swamp',
    'planície': 'Plains',
    'planicie': 'Plains',
    'despacho': 'Swords to Plowshares',
    'despachar': 'Swords to Plowshares',
    'caminho': 'Path to Exile',
    'caminho para o exilio': 'Path to Exile',
    'raio negro': 'Black Lightning',
    'raios': 'Lightning Bolt',
    'bola de fogo': 'Fireball',
    'furacao': 'Hurricane',
    'furacão': 'Hurricane',
    'conflagração': 'Conflagrate',
    'pregar': 'Pillage',
    'ressurgir': 'Reanimate',
    'reanimar': 'Reanimate',
};

module.exports = {
    PORT: process.env.PORT || 3000,
    SCRYFALL_DELAY,
    SCRYFALL_BASE_URL: 'https://api.scryfall.com',
    DICIONARIO_PT_EN,
    RATE_LIMIT_MS: 3000,
    RATE_LIMIT_MAX: 1,
    API_CACHE_TTL: 300000,
    ALLOW_GROUPS: process.env.ALLOW_GROUPS === 'true',
    TEMP_DIR: 'temp',
    AUTH_DIR: 'auth_info_baileys',
};